const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const Property = require('./models/Property');
const User = require('./models/User');

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../.env') });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb+srv://maheen:maheen12@homeshub-cluster.gu5wq9f.mongodb.net/homeshub?retryWrites=true&w=majority&appName=HomesHub-cluster';

const sampleProperties = [
  {
    title: "Modern Apartment in DHA",
    location: "DHA, Lahore",
    price: 25000000, // 2.5 Crore
    type: "apartment",
    purpose: "buy",
    beds: 3,
    baths: 3,
    area: "1800 sqft",
    description: "Luxurious apartment in the heart of DHA with modern amenities, 24/7 security, and backup generator.",
    images: ["https://images.unsplash.com/photo-1598928636135-d146006ff4be?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.48,
    lng: 74.39,
    neighborhood: {
      nearby: "Parks, Shopping Mall, Mosque",
      avgPrice: 2.3, // Crore
      safety: "9/10 (Excellent)"
    }
  },
  {
    title: "Luxury Villa in Bahria Town",
    location: "Bahria Town, Islamabad",
    price: 42000000, // 4.2 Crore
    type: "house",
    purpose: "buy",
    beds: 5,
    baths: 6,
    area: "1 Kanal",
    description: "Brand new designer house with imported fittings, swimming pool, and servant quarter.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.58,
    lng: 73.12,
    neighborhood: {
      nearby: "Cinema, Zoo, Hospital",
      avgPrice: 4.0,
      safety: "9.5/10 (Excellent)"
    }
  },
  {
    title: "Beach View Apartment",
    location: "Clifton, Karachi",
    price: 31000000, // 3.1 Crore
    type: "apartment",
    purpose: "buy",
    beds: 2,
    baths: 2,
    area: "1400 sqft",
    description: "Stunning sea view apartment in a high-rise building. Gym, pool, and dedicated parking included.",
    images: ["https://images.unsplash.com/photo-1600593289358-64a495b7e0a4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 24.82,
    lng: 67.03,
    neighborhood: {
      nearby: "Sea View, Mall, Restaurants",
      avgPrice: 3.5,
      safety: "8/10 (Good)"
    }
  },
  {
    title: "Farm House Near Murree Hills",
    location: "Murree Expressway",
    price: 60000000, // 6.0 Crore
    type: "house",
    purpose: "buy",
    beds: 6,
    baths: 7,
    area: "4 Kanal",
    description: "Beautiful vacation home with panoramic mountain views. Ideal for large families or rental income.",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.90,
    lng: 73.39,
    neighborhood: {
      nearby: "Hiking Trails, Resorts",
      avgPrice: 5.5,
      safety: "8.5/10 (Very Good)"
    }
  },
  {
    title: "Prime Commercial Plaza",
    location: "D Ground, Faisalabad",
    price: 18000000, // 1.8 Crore
    type: "commercial",
    purpose: "buy",
    beds: 0,
    baths: 2,
    area: "5 Marla",
    description: "Excellent investment opportunity in a busy commercial hub. High rental yield expected.",
    images: ["https://images.unsplash.com/photo-1497366754035-f200968a6e72?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.41,
    lng: 73.09,
    neighborhood: {
      nearby: "Banks, Offices, Markets",
      avgPrice: 1.9,
      safety: "8/10 (Good)"
    }
  }
  ,
  {
    title: "Upper Portion for Rent – DHA Phase 5",
    location: "DHA Phase 5, Lahore",
    price: 150000,
    type: "house",
    purpose: "rent",
    beds: 3,
    baths: 3,
    area: "Upper Portion",
    description: "Fully furnished upper portion with servant room and car porch. Ideal for families seeking comfort and convenience in DHA Phase 5.",
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.52,
    lng: 74.36,
    neighborhood: { nearby: "Parks, Schools, Shopping Mall", safety: "9/10 (Excellent)" }
  },
  {
    title: "Apartment for Rent – Gulberg III",
    location: "Gulberg III, Lahore",
    price: 95000,
    type: "apartment",
    purpose: "rent",
    beds: 2,
    baths: 2,
    area: "950 sqft",
    description: "Well-maintained apartment with lift, standby generator, and 24/7 security in Gulberg III.",
    images: ["https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.54,
    lng: 74.34,
    neighborhood: { nearby: "Restaurants, Malls, Metro Station", safety: "8.5/10 (Very Good)" }
  },
  {
    title: "House for Sale – Bahria Town Lahore",
    location: "Bahria Town, Lahore",
    price: 48000000,
    type: "house",
    purpose: "buy",
    beds: 4,
    baths: 4,
    area: "10 Marla",
    description: "Brand new modern elevation house with premium finishes and smart layout, located in a prime Bahria Town sector.",
    images: ["https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.40,
    lng: 74.20,
    neighborhood: { nearby: "Parks, Community Center, Hospitals", avgPrice: 4.6, safety: "9/10 (Excellent)" }
  },
  {
    title: "Commercial Plaza for Sale – Model Town",
    location: "Model Town, Lahore",
    price: 120000000,
    type: "commercial",
    purpose: "buy",
    beds: 0,
    baths: 4,
    area: "3 Floors",
    description: "Corner commercial plaza ideal for corporate offices or retail brands. High visibility and footfall.",
    images: ["https://images.unsplash.com/photo-1582582494707-572d8fefb23b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.49,
    lng: 74.32,
    neighborhood: { nearby: "Banks, Markets, Public Transport", avgPrice: 11.5, safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Residential Plot – LDA Avenue 1",
    location: "LDA Avenue 1, Lahore",
    price: 26000000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "1 Kanal",
    description: "Clear possession, prime location residential plot in LDA Avenue 1. Ideal for building your dream home.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.41,
    lng: 74.28,
    neighborhood: { nearby: "Parks, Schools, Mosque", avgPrice: 2.6, safety: "8/10 (Good)" }
  },
  {
    title: "House for Rent – G-13",
    location: "G-13, Islamabad",
    price: 180000,
    type: "house",
    purpose: "rent",
    beds: 5,
    baths: 5,
    area: "12 Marla",
    description: "Spacious house with lawn and ample parking in G-13. Ideal for large families.",
    images: ["https://images.unsplash.com/photo-1499951360447-5c5b90b0a399?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.69,
    lng: 73.04,
    neighborhood: { nearby: "Schools, Parks, Markets", safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Apartment for Rent – E-11",
    location: "E-11, Islamabad",
    price: 85000,
    type: "apartment",
    purpose: "rent",
    beds: 2,
    baths: 2,
    area: "900 sqft",
    description: "Luxury apartment with backup power and CCTV. Excellent building management.",
    images: ["https://images.unsplash.com/photo-1582582494707-572d8fefb23b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.71,
    lng: 73.04,
    neighborhood: { nearby: "Mosque, Supermarket, Park", safety: "8/10 (Good)" }
  },
  {
    title: "House for Sale – Bahria Enclave",
    location: "Bahria Enclave, Islamabad",
    price: 72000000,
    type: "house",
    purpose: "buy",
    beds: 5,
    baths: 6,
    area: "1 Kanal",
    description: "Designer interior with premium fixtures and landscaped lawn in Bahria Enclave.",
    images: ["https://images.unsplash.com/photo-1505691723518-36a3ae0f1d41?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.72,
    lng: 73.12,
    neighborhood: { nearby: "Community Center, Hospital, School", avgPrice: 7.0, safety: "9/10 (Excellent)" }
  },
  {
    title: "Apartment for Sale – F-10",
    location: "F-10, Islamabad",
    price: 31000000,
    type: "apartment",
    purpose: "buy",
    beds: 3,
    baths: 3,
    area: "1650 sqft",
    description: "3-bed apartment with Margalla views and reserved parking. Prime location.",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.71,
    lng: 73.04,
    neighborhood: { nearby: "Parks, Restaurants, Mall", avgPrice: 3.0, safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Residential Plot – G-15",
    location: "G-15, Islamabad",
    price: 18500000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "10 Marla",
    description: "Corner plot with wide road access in G-15 residential sector.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.69,
    lng: 73.02,
    neighborhood: { nearby: "Schools, Market, Mosque", avgPrice: 1.9, safety: "8/10 (Good)" }
  },
  {
    title: "House for Rent – Cantt",
    location: "Cantt, Multan",
    price: 90000,
    type: "house",
    purpose: "rent",
    beds: 4,
    baths: 4,
    area: "Double Storey",
    description: "Well-built double storey house in Multan Cantt. Peaceful neighborhood and secure environment.",
    images: ["https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.20,
    lng: 71.47,
    neighborhood: { nearby: "Parks, Market, Mosque", safety: "8/10 (Good)" }
  },
  {
    title: "Shop for Rent – Hussain Agahi",
    location: "Hussain Agahi, Multan",
    price: 120000,
    type: "commercial",
    purpose: "rent",
    beds: 0,
    baths: 1,
    area: "600 sqft",
    description: "High footfall commercial shop ideal for retail. Prime street frontage.",
    images: ["https://images.unsplash.com/photo-1582582494707-572d8fefb23b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.20,
    lng: 71.48,
    neighborhood: { nearby: "Banks, Markets", safety: "8/10 (Good)" }
  },
  {
    title: "House for Sale – Royal Orchard",
    location: "Royal Orchard, Multan",
    price: 21000000,
    type: "house",
    purpose: "buy",
    beds: 4,
    baths: 4,
    area: "10 Marla",
    description: "Newly built modern home with spacious rooms and quality fixtures in Royal Orchard.",
    images: ["https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.22,
    lng: 71.49,
    neighborhood: { nearby: "Community Park, School", avgPrice: 2.0, safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Commercial Building for Sale – Boson Road",
    location: "Boson Road, Multan",
    price: 65000000,
    type: "commercial",
    purpose: "buy",
    beds: 0,
    baths: 4,
    area: "4 Floors",
    description: "Income-generating commercial building on Boson Road. Strong rental yield and tenant mix.",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.21,
    lng: 71.49,
    neighborhood: { nearby: "Banks, Commercial Hub", avgPrice: 6.2, safety: "8/10 (Good)" }
  },
  {
    title: "Residential Plot – Wapda Town",
    location: "Wapda Town, Multan",
    price: 14000000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "1 Kanal",
    description: "Prime location plot with clear possession in Wapda Town.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.19,
    lng: 71.47,
    neighborhood: { nearby: "Park, Mosque", avgPrice: 1.4, safety: "8/10 (Good)" }
  },
  {
    title: "Apartment for Rent – Clifton Block 5",
    location: "Clifton Block 5, Karachi",
    price: 160000,
    type: "apartment",
    purpose: "rent",
    beds: 3,
    baths: 3,
    area: "Sea-facing",
    description: "Sea-facing 3-bed apartment with modern kitchen and reserved parking in Clifton.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 24.85,
    lng: 67.02,
    neighborhood: { nearby: "Beach, Restaurants, Mall", safety: "8/10 (Good)" }
  },
  {
    title: "Office for Rent – PECHS",
    location: "PECHS, Karachi",
    price: 140000,
    type: "commercial",
    purpose: "rent",
    beds: 0,
    baths: 2,
    area: "1200 sqft",
    description: "Well-lit office space with parking available in central PECHS.",
    images: ["https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 24.86,
    lng: 67.04,
    neighborhood: { nearby: "Banks, Cafes, Public Transport", safety: "8/10 (Good)" }
  },
  {
    title: "House for Sale – Gulshan-e-Iqbal",
    location: "Gulshan-e-Iqbal, Karachi",
    price: 39000000,
    type: "house",
    purpose: "buy",
    beds: 4,
    baths: 4,
    area: "240 sq.yds",
    description: "West open house with spacious layout and prime neighborhood access.",
    images: ["https://images.unsplash.com/photo-1505691723518-36a3ae0f1d41?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 24.91,
    lng: 67.10,
    neighborhood: { nearby: "Parks, Schools, Markets", avgPrice: 3.8, safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Apartment for Sale – DHA Phase 6",
    location: "DHA Phase 6, Karachi",
    price: 45000000,
    type: "apartment",
    purpose: "buy",
    beds: 3,
    baths: 3,
    area: "Luxury Flat",
    description: "3-bed luxury flat with modern amenities and reserved parking in DHA Phase 6.",
    images: ["https://images.unsplash.com/photo-1529400971008-adc9f59b0f89?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 24.83,
    lng: 67.05,
    neighborhood: { nearby: "Parks, Cafes, Shopping", avgPrice: 4.4, safety: "9/10 (Excellent)" }
  },
  {
    title: "Commercial Plot – Scheme 33",
    location: "Scheme 33, Karachi",
    price: 28000000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "400 sq.yds",
    description: "Commercial plot in Scheme 33 with wide road approach. Ideal for development.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 24.94,
    lng: 67.16,
    neighborhood: { nearby: "Markets, Main Road", avgPrice: 2.7, safety: "8/10 (Good)" }
  },
  {
    title: "House for Rent – Satellite Town",
    location: "Satellite Town, Quetta",
    price: 55000,
    type: "house",
    purpose: "rent",
    beds: 3,
    baths: 3,
    area: "5 Marla",
    description: "Neat and tidy house suitable for small families in Satellite Town.",
    images: ["https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.19,
    lng: 66.97,
    neighborhood: { nearby: "Market, Mosque, School", safety: "7.5/10 (Good)" }
  },
  {
    title: "Shop for Rent – Jinnah Road",
    location: "Jinnah Road, Quetta",
    price: 90000,
    type: "commercial",
    purpose: "rent",
    beds: 0,
    baths: 1,
    area: "500 sqft",
    description: "Prime location commercial shop on Jinnah Road with excellent frontage.",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.21,
    lng: 66.99,
    neighborhood: { nearby: "Banks, Markets", safety: "7.5/10 (Good)" }
  },
  {
    title: "House for Sale – Samungli Road",
    location: "Samungli Road, Quetta",
    price: 12000000,
    type: "house",
    purpose: "buy",
    beds: 3,
    baths: 3,
    area: "5 Marla",
    description: "Well-located house with easy access to main Samungli Road.",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.20,
    lng: 66.98,
    neighborhood: { nearby: "Parks, Schools", avgPrice: 1.1, safety: "8/10 (Good)" }
  },
  {
    title: "Warehouse for Sale – Sariab Road",
    location: "Sariab Road, Quetta",
    price: 27000000,
    type: "commercial",
    purpose: "buy",
    beds: 0,
    baths: 2,
    area: "Warehouse",
    description: "Ideal warehouse facility for storage and logistics on Sariab Road.",
    images: ["https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.18,
    lng: 66.97,
    neighborhood: { nearby: "Industrial Area, Main Road", avgPrice: 2.6, safety: "7.5/10 (Good)" }
  },
  {
    title: "Residential Plot – Airport Road",
    location: "Airport Road, Quetta",
    price: 8500000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "10 Marla",
    description: "Residential plot near Airport Road with clear access and documents.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 30.23,
    lng: 66.94,
    neighborhood: { nearby: "Airport, Markets", avgPrice: 0.85, safety: "8/10 (Good)" }
  }
  ,
  {
    title: "House for Rent – Peoples Colony",
    location: "Peoples Colony, Faisalabad",
    price: 65000,
    type: "house",
    purpose: "rent",
    beds: 3,
    baths: 3,
    area: "5 Marla",
    description: "Family home in Peoples Colony with nearby schools and markets.",
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.41,
    lng: 73.09,
    neighborhood: { nearby: "Schools, Markets, Parks", safety: "8/10 (Good)" }
  },
  {
    title: "Factory Unit for Rent – Sargodha Road",
    location: "Sargodha Road, Faisalabad",
    price: 250000,
    type: "commercial",
    purpose: "rent",
    beds: 0,
    baths: 2,
    area: "Industrial Unit",
    description: "Factory unit with industrial electricity and large loading area.",
    images: ["https://images.unsplash.com/photo-1563865436878-3a3d2b04a279?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.43,
    lng: 73.07,
    neighborhood: { nearby: "Industrial Area, Main Road", safety: "8/10 (Good)" }
  },
  {
    title: "House for Sale – Canal Road",
    location: "Canal Road, Faisalabad",
    price: 24000000,
    type: "house",
    purpose: "buy",
    beds: 4,
    baths: 4,
    area: "10 Marla",
    description: "Modern home on Canal Road with premium fixtures and spacious layout.",
    images: ["https://images.unsplash.com/photo-1505691723518-36a3ae0f1d41?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.42,
    lng: 73.08,
    neighborhood: { nearby: "Parks, Schools, Market", avgPrice: 2.3, safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Plaza for Sale – D-Ground",
    location: "D-Ground, Faisalabad",
    price: 80000000,
    type: "commercial",
    purpose: "buy",
    beds: 0,
    baths: 4,
    area: "Fully Rented",
    description: "Fully rented commercial plaza in D-Ground with strong yield.",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.41,
    lng: 73.09,
    neighborhood: { nearby: "Banks, Offices, Markets", avgPrice: 7.8, safety: "8/10 (Good)" }
  },
  {
    title: "Industrial Plot – M-3 Industrial City",
    location: "M-3 Industrial City, Faisalabad",
    price: 32000000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "1 Kanal",
    description: "Industrial plot suitable for factory or warehouse development.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 31.47,
    lng: 73.11,
    neighborhood: { nearby: "Industrial Zone, Main Road", avgPrice: 3.1, safety: "8/10 (Good)" }
  },
  {
    title: "House for Rent – Hayatabad Phase 3",
    location: "Hayatabad Phase 3, Peshawar",
    price: 85000,
    type: "house",
    purpose: "rent",
    beds: 5,
    baths: 5,
    area: "10 Marla",
    description: "Spacious family home in Hayatabad Phase 3 with nearby parks.",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.01,
    lng: 71.53,
    neighborhood: { nearby: "Parks, Schools, Markets", safety: "8/10 (Good)" }
  },
  {
    title: "Office for Rent – University Road",
    location: "University Road, Peshawar",
    price: 70000,
    type: "commercial",
    purpose: "rent",
    beds: 0,
    baths: 1,
    area: "900 sqft",
    description: "Office space with easy access and parking on University Road.",
    images: ["https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.00,
    lng: 71.54,
    neighborhood: { nearby: "Banks, Cafes, Public Transport", safety: "8/10 (Good)" }
  },
  {
    title: "House for Sale – Regi Model Town",
    location: "Regi Model Town, Peshawar",
    price: 19000000,
    type: "house",
    purpose: "buy",
    beds: 4,
    baths: 4,
    area: "7 Marla",
    description: "Well-planned house with modern design in Regi Model Town.",
    images: ["https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.02,
    lng: 71.53,
    neighborhood: { nearby: "Parks, Schools", avgPrice: 1.8, safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Commercial Plaza for Sale – Saddar",
    location: "Saddar, Peshawar",
    price: 55000000,
    type: "commercial",
    purpose: "buy",
    beds: 0,
    baths: 4,
    area: "High Yield",
    description: "Commercial plaza with high rental yield in Saddar business district.",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.00,
    lng: 71.54,
    neighborhood: { nearby: "Banks, Offices, Markets", avgPrice: 5.3, safety: "8/10 (Good)" }
  },
  {
    title: "Residential Plot – Hayatabad",
    location: "Hayatabad, Peshawar",
    price: 13000000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "10 Marla",
    description: "Residential plot in Hayatabad with prime access.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.01,
    lng: 71.52,
    neighborhood: { nearby: "Parks, Mosque, Market", avgPrice: 1.3, safety: "8/10 (Good)" }
  },
  {
    title: "House for Rent – Model Town A",
    location: "Model Town A, Bahawalpur",
    price: 45000,
    type: "house",
    purpose: "rent",
    beds: 3,
    baths: 3,
    area: "5 Marla",
    description: "Family house in Model Town A near schools and parks.",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 29.40,
    lng: 71.68,
    neighborhood: { nearby: "Schools, Parks, Market", safety: "8/10 (Good)" }
  },
  {
    title: "Shop for Rent – Circular Road",
    location: "Circular Road, Bahawalpur",
    price: 65000,
    type: "commercial",
    purpose: "rent",
    beds: 0,
    baths: 1,
    area: "450 sqft",
    description: "Retail shop on Circular Road with strong footfall.",
    images: ["https://images.unsplash.com/photo-1582582494707-572d8fefb23b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 29.39,
    lng: 71.67,
    neighborhood: { nearby: "Banks, Markets", safety: "8/10 (Good)" }
  },
  {
    title: "House for Sale – Satellite Town",
    location: "Satellite Town, Bahawalpur",
    price: 14000000,
    type: "house",
    purpose: "buy",
    beds: 4,
    baths: 4,
    area: "8 Marla",
    description: "Well-built house in Satellite Town near community facilities.",
    images: ["https://images.unsplash.com/photo-1505691723518-36a3ae0f1d41?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 29.41,
    lng: 71.70,
    neighborhood: { nearby: "Parks, Schools, Markets", avgPrice: 1.35, safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Farm House for Sale – Ahmedpur Road",
    location: "Ahmedpur Road, Bahawalpur",
    price: 60000000,
    type: "house",
    purpose: "buy",
    beds: 3,
    baths: 3,
    area: "1 Acre",
    description: "Beautiful farm house with ample land and serene surroundings on Ahmedpur Road.",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 29.37,
    lng: 71.63,
    neighborhood: { nearby: "Resorts, Main Road", avgPrice: 5.8, safety: "8/10 (Good)" }
  },
  {
    title: "Residential Plot – Dubai Chowk",
    location: "Dubai Chowk, Bahawalpur",
    price: 7000000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "10 Marla",
    description: "Residential plot near Dubai Chowk with clear possession.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 29.39,
    lng: 71.68,
    neighborhood: { nearby: "Market, Mosque", avgPrice: 0.7, safety: "8/10 (Good)" }
  },
  {
    title: "House for Rent – Civil Lines",
    location: "Civil Lines, Gujrat",
    price: 50000,
    type: "house",
    purpose: "rent",
    beds: 3,
    baths: 3,
    area: "5 Marla",
    description: "Comfortable family house in Civil Lines near schools.",
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 32.58,
    lng: 74.08,
    neighborhood: { nearby: "Schools, Markets", safety: "8/10 (Good)" }
  },
  {
    title: "Shop for Rent – GT Road",
    location: "GT Road, Gujrat",
    price: 80000,
    type: "commercial",
    purpose: "rent",
    beds: 0,
    baths: 1,
    area: "500 sqft",
    description: "Retail shop on GT Road with strong visibility.",
    images: ["https://images.unsplash.com/photo-1582582494707-572d8fefb23b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 32.58,
    lng: 74.09,
    neighborhood: { nearby: "Banks, Markets", safety: "8/10 (Good)" }
  },
  {
    title: "House for Sale – Service Mor",
    location: "Service Mor, Gujrat",
    price: 11000000,
    type: "house",
    purpose: "buy",
    beds: 3,
    baths: 3,
    area: "5 Marla",
    description: "Compact and modern home near Service Mor.",
    images: ["https://images.unsplash.com/photo-1505691723518-36a3ae0f1d41?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 32.57,
    lng: 74.07,
    neighborhood: { nearby: "Parks, Schools", avgPrice: 1.05, safety: "8/10 (Good)" }
  },
  {
    title: "Plaza for Sale – Fawara Chowk",
    location: "Fawara Chowk, Gujrat",
    price: 42000000,
    type: "commercial",
    purpose: "buy",
    beds: 0,
    baths: 4,
    area: "Prime Commercial",
    description: "Commercial plaza in the heart of Fawara Chowk.",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 32.58,
    lng: 74.08,
    neighborhood: { nearby: "Banks, Offices, Markets", avgPrice: 4.1, safety: "8/10 (Good)" }
  },
  {
    title: "Residential Plot – Marghzar Colony",
    location: "Marghzar Colony, Gujrat",
    price: 6500000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "10 Marla",
    description: "Residential plot in Marghzar Colony with clear possession.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 32.58,
    lng: 74.09,
    neighborhood: { nearby: "Market, Mosque", avgPrice: 0.65, safety: "8/10 (Good)" }
  },
  {
    title: "Apartment for Rent – Sector D-4",
    location: "Sector D-4, Mirpur (AJK)",
    price: 55000,
    type: "apartment",
    purpose: "rent",
    beds: 2,
    baths: 2,
    area: "850 sqft",
    description: "Apartment in Sector D-4 with nearby amenities.",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.15,
    lng: 73.75,
    neighborhood: { nearby: "Parks, Markets", safety: "8/10 (Good)" }
  },
  {
    title: "House for Rent – Islamgarh",
    location: "Islamgarh, Mirpur (AJK)",
    price: 70000,
    type: "house",
    purpose: "rent",
    beds: 3,
    baths: 3,
    area: "7 Marla",
    description: "Family house in Islamgarh with secure neighborhood.",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.13,
    lng: 73.78,
    neighborhood: { nearby: "Market, Mosque", safety: "8/10 (Good)" }
  },
  {
    title: "House for Sale – New Mirpur City",
    location: "New Mirpur City, Mirpur (AJK)",
    price: 18000000,
    type: "house",
    purpose: "buy",
    beds: 4,
    baths: 4,
    area: "7 Marla",
    description: "Modern house in New Mirpur City with quality finishes.",
    images: ["https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.14,
    lng: 73.75,
    neighborhood: { nearby: "Parks, Schools", avgPrice: 1.75, safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Plaza for Sale – Allama Iqbal Road",
    location: "Allama Iqbal Road, Mirpur (AJK)",
    price: 60000000,
    type: "commercial",
    purpose: "buy",
    beds: 0,
    baths: 4,
    area: "Prime Commercial",
    description: "Commercial plaza on Allama Iqbal Road with excellent rental income.",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.15,
    lng: 73.76,
    neighborhood: { nearby: "Banks, Offices, Markets", avgPrice: 5.8, safety: "8/10 (Good)" }
  },
  {
    title: "Residential Plot – Sector F-2",
    location: "Sector F-2, Mirpur (AJK)",
    price: 9500000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "10 Marla",
    description: "Residential plot in Sector F-2 with clear possession.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 33.16,
    lng: 73.74,
    neighborhood: { nearby: "Market, Mosque", avgPrice: 0.95, safety: "8/10 (Good)" }
  },
  {
    title: "House for Rent – Upper Plate",
    location: "Upper Plate, Muzaffarabad",
    price: 45000,
    type: "house",
    purpose: "rent",
    beds: 3,
    baths: 3,
    area: "5 Marla",
    description: "Family house in Upper Plate near local amenities.",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.37,
    lng: 73.47,
    neighborhood: { nearby: "Parks, Markets", safety: "8/10 (Good)" }
  },
  {
    title: "Guest House for Rent – Neelum Road",
    location: "Neelum Road, Muzaffarabad",
    price: 120000,
    type: "commercial",
    purpose: "rent",
    beds: 6,
    baths: 6,
    area: "Guest House",
    description: "Guest house on Neelum Road ideal for tourism with ample rooms.",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.39,
    lng: 73.51,
    neighborhood: { nearby: "Tourist Spots, Main Road", safety: "8/10 (Good)" }
  },
  {
    title: "House for Sale – Lower Chattar",
    location: "Lower Chattar, Muzaffarabad",
    price: 16000000,
    type: "house",
    purpose: "buy",
    beds: 4,
    baths: 4,
    area: "8 Marla",
    description: "Well-built house in Lower Chattar with scenic surroundings.",
    images: ["https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.36,
    lng: 73.48,
    neighborhood: { nearby: "Parks, Schools", avgPrice: 1.55, safety: "8.5/10 (Very Good)" }
  },
  {
    title: "Hotel Property for Sale – Patikka",
    location: "Patikka, Muzaffarabad",
    price: 90000000,
    type: "commercial",
    purpose: "buy",
    beds: 0,
    baths: 10,
    area: "Hotel",
    description: "Hotel property at tourist location in Patikka with strong potential.",
    images: ["https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.47,
    lng: 73.62,
    neighborhood: { nearby: "Tourist Spots, Main Road", avgPrice: 8.7, safety: "8/10 (Good)" }
  },
  {
    title: "Scenic Residential Plot – Neelum Valley",
    location: "Neelum Valley, Muzaffarabad",
    price: 12000000,
    type: "plot",
    purpose: "buy",
    beds: 0,
    baths: 0,
    area: "1 Kanal",
    description: "Scenic residential plot in Neelum Valley ideal for a vacation home.",
    images: ["https://images.unsplash.com/photo-1560067174-f5c15e6d8c3b?auto=format&fit=crop&w=1200"],
    contactEmail: "maheenrauf55@gmail.com",
    lat: 34.59,
    lng: 73.93,
    neighborhood: { nearby: "River, Resorts", avgPrice: 1.2, safety: "8/10 (Good)" }
  }
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB for seeding');

    // Create a demo user if not exists
    let user = await User.findOne({ email: 'demo@homeshub.com' });
    if (!user) {
      user = await User.create({
        name: 'Demo Admin',
        email: 'demo@homeshub.com',
        password: 'password123',
        phone: '03001234567',
        role: 'admin'
      });
      console.log('👤 Created demo user');
    }

    // Clear existing properties (optional, commenting out to append instead)
    // await Property.deleteMany({}); 
    // console.log('🗑️ Cleared existing properties');

    // Check if properties already exist to avoid duplicates
    const existingCount = await Property.countDocuments();
    if (existingCount > 0) {
      console.log(`ℹ️ Database already has ${existingCount} properties. Appending new ones if they don't exist...`);
    }

    let addedCount = 0;
    let updatedCount = 0;
    for (const prop of sampleProperties) {
      const result = await Property.findOneAndUpdate(
        { title: prop.title },
        { ...prop, postedBy: user._id },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
      
      if (result.isNew) {
        addedCount++;
      } else {
        updatedCount++;
      }
    }

    console.log(`✨ Successfully added ${addedCount} and updated ${updatedCount} sample properties!`);
    
    // Disconnect
    await mongoose.disconnect();
    console.log('👋 Database connection closed');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error);
    process.exit(1);
  }
};

seedDatabase();
